#
---
services:
  nfexplorer:
    image: nfexplorer:0.1
    ports:
      - "2931:8080/tcp"
      - "12345:9995/udp"
    env_file:
      - .env
    volumes:
      - ./data:/app/flow-data
      - ./logs:/app/logs
      - ./config:/app/config

